spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: AuthDB
        password: Auth123456
        url: jdbc:mysql://localhost:3306/AuthControl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto:create


server:
    port: 8080
    servlet:
        session:
            timeout: 10


logging:
    file:
        path: "./log"

